"""Add admin profile and assignment attribution

Revision ID: 47b7e825d86a
Revises: c78c10818839
Create Date: 2026-08-17 13:27:42.970245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b7e825d86a'
down_revision: Union[str, Sequence[str], None] = 'c78c10818839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('name', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('role', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('assigned_by_admin_id', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('returned_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'admins', ['returned_by_admin_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'admins', ['assigned_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'returned_by_admin_id')
    op.drop_column('assignments', 'assigned_by_admin_id')
    op.drop_column('admins', 'role')
    op.drop_column('admins', 'name')
    # ### end Alembic commands ###
